# Generated by Django 5.0.4 on 2024-04-15 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_pdf_file',
            field=models.FileField(blank=True, upload_to='pdfs/'),
        ),
    ]
