# Generated by Django 5.0.4 on 2024-04-19 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='readers',
        ),
    ]
