# Generated by Django 5.0.4 on 2024-04-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_remove_book_readers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='is_approved',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
