# Generated by Django 5.0.4 on 2024-04-19 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'permissions': [('can_view_request', 'Can view request'), ('can_edit_request', 'Can edit request'), ('can_delete_request', 'Can delete request'), ('can_add_request', 'Can add request')]},
        ),
    ]
