# Generated by Django 5.0.4 on 2024-04-24 08:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_alter_request_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='request_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
