# Generated by Django 5.0.4 on 2024-04-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='return_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
